### ISSUE TITLE
/new not accepting repos without 5 issues

### ISSUE THREAD

**Issue by avipars** [oasis-sh/oasis#77]
a repo without 5 issues isn't accepted... In addition a repo that only recently got 5 issues doesn't get accepted either.

**Comment by heybereket** [comment]
Hey, as of now we're setting the minimum issues to 5 but this can change very soon - and we get all data from GitHub API, so it may take a bit for it to update. Which repo are you trying to add? I may be able to assist.

**Comment by avipars** [comment]
Makes sense, thank you!

**Comment by yhdesai** [comment]
I am curious to know why is this based on the number of issues rather than the number of stars? I've always seen others use stars as the metric, Any specific reason for using the number of issues as the metric?

**Comment by heybereket** [comment]
> I am curious to know why is this based on the number of issues rather than the number of stars? I've always seen others use stars as the metric, Any specific reason for using the number of issues as the metric?

Not everyone stars repositories and it shouldn't be based on that because for newer projects that's not fair as they might have a good readme, and be open to taking contributors but only have a few stars or maybe none at all. 

Issues can determine if there are things that need to be worked on, we're still thinking of a possible better way to determine this but as of now we've made it 5+ issues, and not stars for the reason I gave here. If you have any questions about this, feel free to let me know.

**Comment by yhdesai** [comment]
Ah yes, it makes sense to have the metric as issues if the focus is on getting contributors. The website landing page made seem like it was something like a social network for developers so got a bit confused.

**Comment by heybereket** [comment]
> Ah yes, it makes sense to have the metric as issues if the focus is on getting contributors. The website landing page made seem like it was something like a social network for developers so got a bit confused.

Oh yeah, it is. It's a developer platform community, this issue was for the original idea of the project that is no longer the case.
So yes, it's a social network.

**Comment by f1shy-dev** [comment]
Closing this issue.

In the new version we may do something like:

You can add any repo, but if it's under a certain point level (mix of stars, non-bot prs and non-bot issues and other factors), it would be added but would require moderator verification. (To prevent bots)

the 5 issue requirement was originally to used as a requirement so new people had somewhere to go, but since we're shifting the overall idea of the project, this exact limit will be removed.
